name: CI

on: [push, pull_request]

jobs:
  lint-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Runs shell script static analysis
        run: |
          sudo apt-get install shellcheck
          ./run-tests.sh --check-shellscript
  
  lint-black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check Python code formatting
        run: |
          pip install black
          ./run-tests.sh --check-black

  lint-pydocstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check compliance with Python docstring conventions
        run: |
          pip install --upgrade pip
          pip install pydocstyle
          ./run-tests.sh --check-pydocstyle
